# Comment
source 'https://rubygems.org'

gem 'rails', '3.2.1'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'ruby-debug19', :require => 'ruby-debug', :group => :test

gem "rspec", ">= 2.5.0", :group => [:test, :development]

group :test do
  gem "guard-spork"
end
